spring:
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://134.175.16.143:3306/dbTest?useSSL=false
    username: schoolhelp6!
    password: Zgdr@Very6!

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true